name: Deployment (production)

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    uses: ./.github/workflows/build.yml
    needs:
      - tests
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs:
      - build
    with:
      environment: production
      secrets: inherit